# Basics of NumPy
- NumPy - Introduction and Installation
- NumPy - Arrays Data Structure ( 1D, 2D, ND arrays)
- Creating Arrays
- NumPy - Data Types
- Array Attributes
- Creating Arrays – Alternative Ways
- Sub-setting, Slicing and Indexing Arrays
- Operations on Arrays
- Array Manipulation


### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing numpy

!pip install numpy

#### Importing numpy

In [1]:
import numpy as np

### Arrays Data Structure

An `Array` is combination of homogenous data objects and can be indexed across multiple dimensions

#### Arrays are –
- ordered sequence/collection of Homogenous data
- multidimensional
- mutable


#### Creating Arrays – From list/tuple

- `np.array()` is used to create a numpy array from a list


#### Example on 1-D Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Example on 2-D Array

In [3]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Array Attributes

- Attributes are the features/characteristics of an object that describes the object

- Some of the attributes of the numpy array are:
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type


In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.shape

(3, 4)

In [6]:
arr.size

12

In [7]:
arr.ndim

2

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### Indexing, Slicing and Boolen Indexing

In [10]:
arr = np.random.randint(5, 50, size = 10)
arr

array([17, 37,  8, 10, 18, 49, 30, 49, 31, 15], dtype=int32)

#### 1-D Arrays

###### Ex. Extract first 3 elements

In [11]:
arr[0:3]

array([17, 37,  8], dtype=int32)

###### Ex. Extract last 5 elements

In [12]:
arr[-5 :]

array([49, 30, 49, 31, 15], dtype=int32)

###### Ex. Extract elements at index position 2, 5, 9.

In [13]:
arr[[2, 5, 9]]

array([ 8, 49, 15], dtype=int32)

###### Ex. Extract elements less than 20

In [15]:
arr[arr < 20]

array([17,  8, 10, 18, 15], dtype=int32)

### 2-D Arrays

In [16]:
arr = np.random.randint(5, 50, size = (6,4))
arr

array([[49, 38, 48, 17],
       [48, 24, 48, 11],
       [44, 11, 35, 16],
       [34,  5, 22, 28],
       [42, 16, 48, 47],
       [ 7, 20, 41, 48]], dtype=int32)

###### Ex. Extract first 3 rows

In [17]:
arr[0:3]

array([[49, 38, 48, 17],
       [48, 24, 48, 11],
       [44, 11, 35, 16]], dtype=int32)

###### Ex. Extract last 2 rows

In [18]:
arr[-2:]

array([[42, 16, 48, 47],
       [ 7, 20, 41, 48]], dtype=int32)

###### Ex. Extract second column

In [19]:
arr[:, 1]

array([38, 24, 11,  5, 16, 20], dtype=int32)

###### Ex. Extract row 2 and 3 and column 2 and 3

In [20]:
arr[1:3, 1 : 3]

array([[24, 48],
       [11, 35]], dtype=int32)

###### Ex. Extract values less than 25

In [21]:
arr[arr < 25]

array([17, 24, 11, 11, 16,  5, 22, 16,  7, 20], dtype=int32)

###### Ex. Identify largest value. Extract values less than half of largest values

In [25]:
arr[arr < arr.max()/2]

array([17, 24, 11, 11, 16,  5, 22, 16,  7, 20], dtype=int32)

### Examples on Coffee Shop Data Set

#### Coffee Shop

Mr. Alex owns a huge chain of coffee shop franchises. His franchises are spread across various states in India. There are in all 13 products sold across 156 franchises. Each franchise manager records their monthly sales and profits and compares with its corresponding targeted values. Let us start learning various attributes of numpy and pandas using the Coffee Shop dataset.


Fields in dataset -

- Product Name
- Actual Sales
- Actual Profits
- Targeted Sales
- Targeted Profits

#### Ex.  Create an array of coffee products, sales and profits

In [26]:
coffee_products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array( [52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])

###### Ex. How many products are there in the dataset?

In [27]:
coffee_products.size

10

###### Ex.  Sales greater than 50,000

In [28]:
sales[sales > 50000]

array([52248., 71060., 60014., 69925.])

###### Ex.  Identify Losses

In [29]:
profits[profits< 0]

array([-2954.])

###### Ex.  Products in loss

In [45]:
coffee_products[profits< 0]

array(['Green Tea'], dtype='<U17')

In [44]:
var = coffee_products[profits< 0][0]
str(var)

'Green Tea'

###### Ex.  Product with maximum Sales

In [35]:
coffee_products[sales == sales.max()][0]

np.str_('Colombian')

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

### Array Operations

#### Arithmetic operations on Arrays -
 - Addition, Substraction, Multiplication, Division, etc.
 - Operations on array and a scalar value
 - Operations between two arrays
 - Matrix Operations - Multiplication(np.dot()), Transpose(np.transpose())


#### Array and Scalar

In [ ]:
arr1 = np.random.randint(1,10,size = 5)
arr1

In [ ]:
arr1 + 5 # Addition

In [ ]:
arr1 - 5 # Substraction

In [ ]:
arr1 * 5 # Multiplication

In [ ]:
arr1 / 5 # Division

In [ ]:
arr1 // 5 # Floor Division

In [ ]:
arr1 % 5 # Modulus

#### Two Arrays

In [ ]:
arr1 = np.random.randint(1,10,size = 5)
arr1

In [ ]:
arr2 = np.random.randint(1,10,size = 5)
arr2

In [ ]:
arr1 + arr2 # Addition

In [ ]:
arr1 - arr2 # Substraction

In [ ]:
arr1 * arr2 # Multiplication

In [ ]:
arr1 / arr2 # Division

In [ ]:
arr1 // arr2 # Floor Division

In [ ]:
arr1 % arr2 # Modulus

#### Relational operations on Arrays -
 - ==, !=, <, >, <=, >=
 - Operations on array and a scalar value
 - Operations between two arrays

#### Array and Scalar

In [ ]:
arr1 = np.random.randint(1,10,size = 5)
arr1

In [ ]:
arr1 == 5

In [ ]:
arr1 != 5

In [ ]:
arr1 < 5

In [ ]:
arr1 > 5

In [ ]:
arr1 <= 5

In [ ]:
arr1 >= 5

#### Two Arrays

In [ ]:
arr1 = np.random.randint(1,10,size = 5)
arr1

In [ ]:
arr2 = np.random.randint(1,10,size = 5)
arr2

In [ ]:
arr1 == arr2

In [ ]:
arr1 != arr2

In [ ]:
arr1 < arr2

In [ ]:
arr1 > arr2

In [ ]:
arr1 <= arr2

In [ ]:
arr1 >= arr2

#### Logical operations on Arrays -
 - np.logical_or()
 - np.logical_and()
 - np.logical_not()
 - np.logical_xor()

In [ ]:
arr1 = np.random.randint(1,10,size = 5)
arr1

In [ ]:
arr2 = np.random.randint(1,10,size = 5)
arr2

In [ ]:
np.logical_and(arr1 > 5, arr2 > 5)

In [ ]:
np.logical_or(arr1 > 5, arr2 > 5)

In [ ]:
np.logical_not(arr1 > 5)

In [ ]:
np.logical_xor(arr1 > 5, arr2 > 5)

#### Set Operations on Arrays

Applicable to 1-D Ararys only

- np.unique() - Find the unique elements of an array.
- np.in1d() - Test whether each element of a 1-D array is also present in a second array.
- np.intersect1d() - Find the intersection of two arrays.
- np.setdiff1d() - Find the set difference of two arrays.
- np.union1d() - Find the union of two arrays.

### Array Functions/Methods

- np.all(), np.any()
- arr.sum()
- arr.min(), arr.max(), arr.argmin(), arr.agrmax()
- np.round()
- np.mean(), np.median(), np.average(), np.percentile()


### Examples on Coffee Shop Data Set


#### Data

In [ ]:
import numpy as np
products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array([52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

###### Ex. Identify the products meeting the Target Profits

###### Ex. Are the above products meeting their sales target too?

###### Ex. Identify products meeting sales targets bu not profit targets

### Sorting Arrays

### Array Manipulations

- **Changing Shape** – np.reshape()
- **Adding/Removing Elements** – np.append(), np.insert(), np.delete()
- **Splitting Arrays** – np.hsplit(), np.vsplit(), arr_obj.flatten()
- **Sorting Arrays** - arr_obj.sort(), arr_obj.argsort()

In [ ]:
arr = np.arange(1, 13)
arr

#### np.reshape()

In [ ]:
arr = np.reshape(arr, (4, 3))
arr

#### np.append()

In [ ]:
np.append(arr, [10,20,30, 50, 40, 60]) # Flattens the array

In [ ]:
np.append(arr, np.reshape(np.array([10,20,30]), (1, 3)), axis=0) # axis = 0 adds a 2-D array row-wise

In [ ]:
np.append(arr, [[10],[20],[30],[40]], axis=1) # axis = 1 adds a 2-D array column-wise

In [ ]:
arr_to_append = np.reshape(np.array([10,20,30,40]), (4,1))
np.append(arr, arr_to_append, axis = 1)

#### np.insert()

In [ ]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

In [ ]:
np.insert(arr, 1, 5) # Flattens the arr and inserts 5 at index 1

In [ ]:
np.insert(arr, 1, 5, axis=0) # Inserts [5, 5, 5] as row 1

In [ ]:
np.insert(arr, 1, 5, axis=1) # Inserts [5, 5, 5, 5] as column 1

In [ ]:
np.insert(arr, 1, [10, 20, 30, 40], axis=1)

In [ ]:
np.insert(arr, 1, [10, 20, 30], axis=0)

#### np.delete()

In [ ]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

In [ ]:
np.delete(arr, 1) # Flattens the arr and deletes element at index 1

In [ ]:
np.delete(arr, 1, axis=0) # deletes row 1

In [ ]:
np.delete(arr, 1, axis=1) # deletes column 1

In [ ]:
np.delete(arr,[0,2], axis=0) # deletes selected rows

In [ ]:
np.delete(arr,[0,2], axis=1) # deletes selected columns

#### np.hsplit(), np.vsplit()

In [ ]:
arr = np.reshape(np.arange(1, 25), (6,4))
arr

In [ ]:
np.vsplit(arr, 2)

In [ ]:
np.hsplit(arr, 2)

#### flatten()

In [ ]:
arr

In [ ]:
arr.flatten(order = "F") # returns a 1-D array

In [ ]:
help(arr.flatten)

###### Ex. Identify the off-target (Profit) products and print them in descending order of percent target achievement

###### 1. Identify all the products not achieveing targets
2. Find percent target achievement
3. Display them in descending of percentage value