# Basics of NumPy
- NumPy - Introduction and Installation
- NumPy - Arrays Data Structure ( 1D, 2D, ND arrays)
- Creating Arrays
- NumPy - Data Types
- Array Attributes
- Creating Arrays – Alternative Ways
- Sub-setting, Slicing and Indexing Arrays
- Operations on Arrays
- Array Manipulation


### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing numpy

!pip install numpy

#### Importing numpy

In [4]:
import numpy as np

### Arrays Data Structure

An `Array` is combination of homogenous data objects and can be indexed across multiple dimensions

#### Arrays are –
- ordered sequence/collection of Homogenous data
- multidimensional
- mutable


#### Creating Arrays – From list/tuple

- `np.array()` is used to create a numpy array from a list


#### Example on 1-D Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Example on 2-D Array

In [3]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Array Attributes

- Attributes are the features/characteristics of an object that describes the object

- Some of the attributes of the numpy array are:
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type


In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.shape

(3, 4)

In [6]:
arr.size

12

In [7]:
arr.ndim

2

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### Indexing, Slicing and Boolen Indexing

In [10]:
arr = np.random.randint(5, 50, size = 10)
arr

array([17, 37,  8, 10, 18, 49, 30, 49, 31, 15], dtype=int32)

#### 1-D Arrays

###### Ex. Extract first 3 elements

In [11]:
arr[0:3]

array([17, 37,  8], dtype=int32)

###### Ex. Extract last 5 elements

In [12]:
arr[-5 :]

array([49, 30, 49, 31, 15], dtype=int32)

###### Ex. Extract elements at index position 2, 5, 9.

In [13]:
arr[[2, 5, 9]]

array([ 8, 49, 15], dtype=int32)

###### Ex. Extract elements less than 20

In [15]:
arr[arr < 20]

array([17,  8, 10, 18, 15], dtype=int32)

### 2-D Arrays

In [16]:
arr = np.random.randint(5, 50, size = (6,4))
arr

array([[49, 38, 48, 17],
       [48, 24, 48, 11],
       [44, 11, 35, 16],
       [34,  5, 22, 28],
       [42, 16, 48, 47],
       [ 7, 20, 41, 48]], dtype=int32)

###### Ex. Extract first 3 rows

In [17]:
arr[0:3]

array([[49, 38, 48, 17],
       [48, 24, 48, 11],
       [44, 11, 35, 16]], dtype=int32)

###### Ex. Extract last 2 rows

In [18]:
arr[-2:]

array([[42, 16, 48, 47],
       [ 7, 20, 41, 48]], dtype=int32)

###### Ex. Extract second column

In [19]:
arr[:, 1]

array([38, 24, 11,  5, 16, 20], dtype=int32)

###### Ex. Extract row 2 and 3 and column 2 and 3

In [20]:
arr[1:3, 1 : 3]

array([[24, 48],
       [11, 35]], dtype=int32)

###### Ex. Extract values less than 25

In [21]:
arr[arr < 25]

array([17, 24, 11, 11, 16,  5, 22, 16,  7, 20], dtype=int32)

###### Ex. Identify largest value. Extract values less than half of largest values

In [25]:
arr[arr < arr.max()/2]

array([17, 24, 11, 11, 16,  5, 22, 16,  7, 20], dtype=int32)

### Examples on Coffee Shop Data Set

#### Coffee Shop

Mr. Alex owns a huge chain of coffee shop franchises. His franchises are spread across various states in India. There are in all 13 products sold across 156 franchises. Each franchise manager records their monthly sales and profits and compares with its corresponding targeted values. Let us start learning various attributes of numpy and pandas using the Coffee Shop dataset.


Fields in dataset -

- Product Name
- Actual Sales
- Actual Profits
- Targeted Sales
- Targeted Profits

#### Ex.  Create an array of coffee products, sales and profits

In [63]:
coffee_products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array( [52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])

###### Ex. How many products are there in the dataset?

In [27]:
coffee_products.size

10

###### Ex.  Sales greater than 50,000

In [28]:
sales[sales > 50000]

array([52248., 71060., 60014., 69925.])

###### Ex.  Identify Losses

In [29]:
profits[profits< 0]

array([-2954.])

###### Ex.  Products in loss

In [45]:
coffee_products[profits< 0]

array(['Green Tea'], dtype='<U17')

In [44]:
var = coffee_products[profits< 0][0]
str(var)

'Green Tea'

###### Ex.  Product with maximum Sales

In [35]:
coffee_products[sales == sales.max()][0]

np.str_('Colombian')

### Array Operations

#### Arithmetic operations on Arrays -
 - Addition, Substraction, Multiplication, Division, etc.
 - Operations on array and a scalar value
 - Operations between two arrays
 - Matrix Operations - Multiplication(np.dot()), Transpose(np.transpose())


#### Array and Scalar

In [5]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([4, 9, 3, 8, 7], dtype=int32)

In [6]:
arr1 + 5 # Addition

array([ 9, 14,  8, 13, 12], dtype=int32)

In [7]:
arr1 - 5 # Substraction

array([-1,  4, -2,  3,  2], dtype=int32)

In [8]:
arr1 * 5 # Multiplication

array([20, 45, 15, 40, 35], dtype=int32)

In [9]:
arr1 / 5 # Division

array([0.8, 1.8, 0.6, 1.6, 1.4])

In [10]:
arr1 // 5 # Floor Division

array([0, 1, 0, 1, 1], dtype=int32)

In [11]:
arr1 % 5 # Modulus

array([4, 4, 3, 3, 2], dtype=int32)

#### Two Arrays

In [12]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([9, 9, 6, 1, 4], dtype=int32)

In [13]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([1, 4, 6, 3, 1], dtype=int32)

In [14]:
arr1 + arr2 # Addition

array([10, 13, 12,  4,  5], dtype=int32)

In [15]:
arr1 - arr2 # Substraction

array([ 8,  5,  0, -2,  3], dtype=int32)

In [16]:
arr1 * arr2 # Multiplication

array([ 9, 36, 36,  3,  4], dtype=int32)

In [17]:
arr1 / arr2 # Division

array([9.        , 2.25      , 1.        , 0.33333333, 4.        ])

In [18]:
arr1 // arr2 # Floor Division

array([9, 2, 1, 0, 4], dtype=int32)

In [19]:
arr1 % arr2 # Modulus

array([0, 1, 0, 1, 0], dtype=int32)

#### Relational operations on Arrays -
 - ==, !=, <, >, <=, >=
 - Operations on array and a scalar value
 - Operations between two arrays

#### Array and Scalar

In [20]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([8, 8, 3, 3, 8], dtype=int32)

In [21]:
arr1 == 5

array([False, False, False, False, False])

In [22]:
arr1 != 5

array([ True,  True,  True,  True,  True])

In [23]:
arr1 < 5

array([False, False,  True,  True, False])

In [24]:
arr1 > 5

array([ True,  True, False, False,  True])

In [25]:
arr1 <= 5

array([False, False,  True,  True, False])

In [26]:
arr1 >= 5

array([ True,  True, False, False,  True])

#### Two Arrays

In [27]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([9, 3, 2, 7, 2], dtype=int32)

In [28]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([9, 9, 6, 1, 9], dtype=int32)

In [29]:
arr1 == arr2

array([ True, False, False, False, False])

In [30]:
arr1 != arr2

array([False,  True,  True,  True,  True])

In [31]:
arr1 < arr2

array([False,  True,  True, False,  True])

In [32]:
arr1 > arr2

array([False, False, False,  True, False])

In [33]:
arr1 <= arr2

array([ True,  True,  True, False,  True])

In [34]:
arr1 >= arr2

array([ True, False, False,  True, False])

#### Logical operations on Arrays -
 - np.logical_or()
 - np.logical_and()
 - np.logical_not()
 - np.logical_xor()

In [35]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([2, 4, 2, 2, 6], dtype=int32)

In [38]:
arr1 > 5

array([False, False, False, False,  True])

In [36]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([3, 5, 2, 6, 9], dtype=int32)

In [39]:
arr2 > 5

array([False, False, False,  True,  True])

In [37]:
np.logical_and(arr1 > 5, arr2 > 5)

array([False, False, False, False,  True])

In [40]:
np.logical_or(arr1 > 5, arr2 > 5)

array([False, False, False,  True,  True])

In [41]:
np.logical_not(arr1 > 5)

array([ True,  True,  True,  True, False])

In [42]:
np.logical_xor(arr1 > 5, arr2 > 5)

array([False, False, False,  True, False])

#### Set Operations on Arrays

Applicable to 1-D Ararys only

- np.unique() - Find the unique elements of an array.
- np.in1d() - Test whether each element of a 1-D array is also present in a second array.
- np.intersect1d() - Find the intersection of two arrays.
- np.setdiff1d() - Find the set difference of two arrays.
- np.union1d() - Find the union of two arrays.

In [44]:
arr1 = np.random.randint(1, 10, size = 10)
arr1

array([6, 2, 3, 2, 3, 5, 1, 8, 8, 8], dtype=int32)

In [45]:
np.unique(arr1)

array([1, 2, 3, 5, 6, 8], dtype=int32)

In [48]:
np.unique(arr1, return_index = True, return_counts= True)

(array([1, 2, 3, 5, 6, 8], dtype=int32),
 array([6, 1, 2, 5, 0, 7]),
 array([1, 2, 2, 1, 1, 3]))

In [ ]:
num = 8
tup = np.unique(arr1, return_index = True, return_counts= True)
uni_num = tup[0]
frequency = tup[2]

In [69]:
frequency[uni_num == 8]
print(f"{num} is occuring {frequency[uni_num == 8][0]} times")

8 is occuring 3 times


In [70]:
index = list(uni_num).index(8)
print(f"{num} is occuring {frequency[index]} times")

8 is occuring 3 times


In [54]:
lst = [1, 2, 3, 4, 5]

lst[3]

4

In [56]:
lst[3:4][0]

4

In [59]:
uni_num == 8

array([False, False, False, False, False,  True])

In [60]:
frequency[uni_num == 8][0]

np.int64(3)

In [61]:
frequency[5]

np.int64(3)

In [78]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.arange(3, 7)
arr2

array([3, 4, 5, 6])

In [74]:
np.isin(arr1, arr2)

array([False, False,  True,  True])

In [83]:
arr1 = np.random.randint(5, 10, size = (2,3))
arr1

array([[9, 6, 7],
       [8, 8, 8]], dtype=int32)

In [84]:
arr2 = np.random.randint(5, 10, size = (2,3))
arr2

array([[8, 5, 7],
       [6, 8, 8]], dtype=int32)

In [85]:
np.isin(arr1, arr2)

array([[False,  True,  True],
       [ True,  True,  True]])

In [86]:
help(np.isin)

Help on _ArrayFunctionDispatcher in module numpy:

isin(element, test_elements, assume_unique=False, invert=False, *, kind=None)
    Calculates ``element in test_elements``, broadcasting over `element` only.
    Returns a boolean array of the same shape as `element` that is True
    where an element of `element` is in `test_elements` and False otherwise.

    Parameters
    ----------
    element : array_like
        Input array.
    test_elements : array_like
        The values against which to test each value of `element`.
        This argument is flattened if it is an array or array_like.
        See notes for behavior with non-array-like parameters.
    assume_unique : bool, optional
        If True, the input arrays are both assumed to be unique, which
        can speed up the calculation.  Default is False.
    invert : bool, optional
        If True, the values in the returned array are inverted, as if
        calculating `element not in test_elements`. Default is False.
       

In [79]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.arange(3, 7)
arr2

array([3, 4, 5, 6])

In [80]:
np.intersect1d(arr1, arr2)

array([3, 4])

In [81]:
np.setdiff1d(arr1, arr2)

array([1, 2])

In [82]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6])

### Array Functions/Methods

- np.all(), np.any()
- arr.sum()
- arr.min(), arr.max(), arr.argmin(), arr.agrmax()
- np.round()
- np.mean(), np.median(), np.average(), np.percentile()


###### Ex. Product with maximum sales

In [64]:
# If there is exactly 1 product with max sales
sales.argmax()  # - returns index position of largest element

np.int64(2)

In [65]:
# Indexing - returns str object
coffee_products[sales.argmax()]  

np.str_('Colombian')

In [66]:
# If there are multiple products with max sales
sales == sales.max()

array([False, False,  True, False, False, False, False, False, False,
       False])

In [67]:
# Slicing - returns all products matching the condition array object
coffee_products[sales == sales.max()]

array(['Colombian'], dtype='<U17')

In [68]:
coffee_products[sales == sales.max()][0]

np.str_('Colombian')

In [87]:
np.mean(sales)

np.float64(41606.4)

In [88]:
np.sum(sales)

np.float64(416064.0)

In [93]:
marks = np.array([(51, 67, 83), (41, 93, 36), (50, 31, 87), (94, 46, 52), (80, 61, 69), (72, 77, 40), (54, 64, 54), (84, 33, 40), (56, 56, 90), (45, 75, 61)])
marks

array([[51, 67, 83],
       [41, 93, 36],
       [50, 31, 87],
       [94, 46, 52],
       [80, 61, 69],
       [72, 77, 40],
       [54, 64, 54],
       [84, 33, 40],
       [56, 56, 90],
       [45, 75, 61]])

In [101]:
print(np.round(np.sum(marks, axis=1)/3, 2))

[67.   56.67 56.   64.   70.   63.   57.33 52.33 67.33 60.33]


### Examples on Coffee Shop Data Set


#### Data

In [103]:
import numpy as np
products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array([52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

###### Ex. Identify the products meeting the Target Profits

In [105]:
profit_ach = products[profits > target_profits]
profit_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Lemon', 'Mint'],
      dtype='<U17')

###### Ex. Are the above products meeting their sales target too?

In [106]:
sales_ach = products[sales > target_sales]
sales_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Decaf Irish Cream',
       'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'], dtype='<U17')

In [109]:
if np.all(np.isin(profit_ach, sales_ach)) :
    print("Yes")
else:
    print("No")

Yes


###### Ex. Identify products meeting sales targets but not profit targets

In [111]:
if np.all(np.isin(sales_ach, profit_ach)) :
    print("Yes")
else:
    print("No")
    print(np.setdiff1d(sales_ach, profit_ach))

No
['Decaf Irish Cream' 'Green Tea' 'Regular Espresso']


### Sorting Arrays

In [112]:
fruits = np.array(["Apple", "Banana", "Mango"])
price = np.array([80, 30, 50])

In [113]:
np.sort(price)

array([30, 50, 80])

In [115]:
sort_order = np.argsort(price)
sort_order

array([1, 2, 0])

In [116]:
s_fruits = fruits[sort_order]

array(['Banana', 'Mango', 'Apple'], dtype='<U6')

In [117]:
price.sort()

In [118]:
price

array([30, 50, 80])

In [119]:
marks

array([[51, 67, 83],
       [41, 93, 36],
       [50, 31, 87],
       [94, 46, 52],
       [80, 61, 69],
       [72, 77, 40],
       [54, 64, 54],
       [84, 33, 40],
       [56, 56, 90],
       [45, 75, 61]])

In [124]:
np.sort(marks, axis=0)

array([[41, 31, 36],
       [45, 33, 40],
       [50, 46, 40],
       [51, 56, 52],
       [54, 61, 54],
       [56, 64, 61],
       [72, 67, 69],
       [80, 75, 83],
       [84, 77, 87],
       [94, 93, 90]])

In [121]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None, *, stable=None)
    Return a sorted copy of an array.

    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and,
        in general, the actual implementation will vary with data type.
        The 'mergesort' option is retained for backwards compatibility.

        .. versionchanged:: 1.15.0.
           The 'stable' option was added.

    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, sec

### Array Manipulations

- **Changing Shape** – np.reshape()
- **Adding/Removing Elements** – np.append(), np.insert(), np.delete()
- **Splitting Arrays** – np.hsplit(), np.vsplit(), arr_obj.flatten()
- **Sorting Arrays** - arr_obj.sort(), arr_obj.argsort()

In [125]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### np.reshape()

In [126]:
arr = np.reshape(arr, (4, 3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.append()

In [127]:
np.append(arr, [10,20,30, 50, 40, 60]) # Flattens the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 10, 20, 30, 50, 40,
       60])

In [128]:
np.append(arr, np.reshape(np.array([10,20,30]), (1, 3)), axis=0) # axis = 0 adds a 2-D array row-wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [10, 20, 30]])

In [ ]:
np.append(arr, [[10],[20],[30],[40]], axis=1) # axis = 1 adds a 2-D array column-wise

In [129]:
arr_to_append = np.reshape(np.array([10,20,30,40]), (4,1))
np.append(arr, arr_to_append, axis = 1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30],
       [10, 11, 12, 40]])

#### np.insert()

In [130]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
np.insert(arr, 1, 5) # Flattens the arr and inserts 5 at index 1

array([ 1,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
np.insert(arr, 1, 5, axis=0) # Inserts [5, 5, 5] as row 1

array([[ 1,  2,  3],
       [ 5,  5,  5],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [134]:
np.insert(arr, 1, 5, axis=1) # Inserts [5, 5, 5, 5] as column 1

array([[ 1,  5,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  5,  8,  9],
       [10,  5, 11, 12]])

In [137]:
np.insert(arr, 3, [10, 20, 30, 40], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30],
       [10, 11, 12, 40]])

In [138]:
np.insert(arr, 1, [10, 20, 30], axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.delete()

In [139]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [140]:
np.delete(arr, 1) # Flattens the arr and deletes element at index 1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
np.delete(arr, 1, axis=0) # deletes row 1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
np.delete(arr, 1, axis=1) # deletes column 1

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [143]:
np.delete(arr,[0,2], axis=0) # deletes selected rows

array([[ 4,  5,  6],
       [10, 11, 12]])

In [144]:
np.delete(arr,[0,2], axis=1) # deletes selected columns

array([[ 2],
       [ 5],
       [ 8],
       [11]])

#### np.hsplit(), np.vsplit()

In [145]:
arr = np.reshape(np.arange(1, 25), (6,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [147]:
np.vsplit(arr, 2)  # - row wise

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [146]:
np.hsplit(arr, 2)  # - column wise

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

#### flatten()

In [148]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [150]:
arr.flatten() # returns a 1-D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [149]:
arr.flatten(order = "F") # returns a 1-D array

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

In [ ]:
help(arr.flatten)

###### Ex. Identify the off-target (Profit) products and print them in descending order of percent target achievement

1. Identify all the products not achieveing targets
2. Find percent target achievement
3. Display them in descending of percentage value

In [ ]:
off_products = products[profits < target_profits]
off_profits = profits[profits < target_profits]
off_targets = target_profits[profits < target_profits]

percentage = np.round(off_profits/off_targets * 100, 2)
# Replace negative value with 0
percentage[percentage < 0] = 0
percentage

percent = np.sort(percentage)[::-1]
prod = off_products[np.argsort(percentage)[::-1]]

for i, j in zip(prod, percent):
    print(f"{i} has achieved {j}% of its targets")